name: "Dispatcher"

on:
  repository_dispatch:
    types: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NUMBER: ""
      EVENT_TYPE: ""
    steps:

      - name: Get parameters
        run: |
          echo EVENT_TYPE=$(echo ${{ toJSON(github.event.event_type) }}) >> $GITHUB_ENV
          echo NUMBER=$(echo ${{ toJSON(github.event.client_payload.number) }}) >> $GITHUB_ENV

      - name: print json
        run: echo '${{ toJSON(github.event.client_payload.json) }}' > data.json && cat data.json

      - name: print json
        run: echo '${{ toJSON(github.event) }}' > data2.json && cat data2.json