name: 'PR Labels'
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

  push:
    branches:
      - main

  pull_request:
    types: [synchronize, opened, reopened, labeled]
    branches:
      - main
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "${{ toJSON(github) }}"

      - name: Get labels
        run: echo '${{ toJSON(github.event.pull_request.labels) }}' | jq -r 'map(.name)? | join(",")'

      - name: Get autor
        run: |
          echo "${{ github.event.sender.login }}"
          echo "${{ github.event.sender.url }}"
  autor:
    runs-on: ubuntu-latest
    steps:
      - name: Autor
        run: echo "${{ toJSON(github.actor) }}"

  autor_condition:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Autor
        run: echo "${{ toJSON(github.actor) }}"