name: 'PR Labels'
on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, opened, reopened, labeled]
    branches:
      - main
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo ${{ toJSON(github.event) }}

      - name: Get labels
        run: echo ${{ github.event.pull_request.labels }}

      - name: Get autor
        run: |
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.sender.url }}}
  autor:
    runs-on: ubuntu-latest
    steps:
      - name: Autor
        run: echo ${{ toJSON(github.actor) }}