name: 'PR Detect changes'
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled]
    branches:
      - main
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          modules: modules/**

    - name: Files outputs
      run: echo '${{ fromJSON(steps.filter.outputs.modules_count) }}'

    - name: Files
      run: echo '${{ fromJSON(steps.filter.outputs.modules_files) }}'

    - name: Files changes
      run: echo '${{ fromJSON(steps.filter.outputs.changes) }}'

  # JOB to build and test each of modified packages
  build:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo '${{ matrix.package }}'
