name: Test slack notifications
on:
  push:
    branches:
      - main

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Test Output
        id: test_path
        env:
          NEW_PATH: "data"
        run: |
          path="serenity-$(date +%Y.%m.%d-%H.%M.%S)"
          p=$NEW_PATH/$path
          echo "::set-output name=OUTPUT_PATH::$NEW_PATH/$path"

      - name: Send slack notification
        if: ${{ always() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,workflow
          #icon_emoji: ':octocat:'
          author_name: 'Path: <s3://${{ steps.test_path.outputs.output_path }}|s3://${{ steps.test_path.outputs.output_path }}>'
          #text: '*Res:* <http://example.com|my link> :package: \\n *More:* Hi'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
