name: Test slack notifications
on:
  push:
    branches:
      - main

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:

      - name: Send slack notification
        if: ${{ always() }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,workflow
          emoji: ':package:'
          text: '*Res:* <http://example.com|my link> :package: \\n *More:* Hi'
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
                fields: [{
                    title: 'lower case',
                    value: 'LOWER CASE CHECK'.toLowerCase(),
                    short: true
                  },
                  {
                    title: 'reverse',
                    value: 'gnirts esrever'.split('').reverse().join(''),
                    short: true
                  }],
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
