name: Test slack notifications
on:
  push:
    branches:
      - main

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:

      - name: Send slack notification
        if: ${{ always() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,workflow
          emoji: ':package:'
          text: '**Res:** <http://example.com|my link>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
