name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch: {}
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          #days-before-issue-stale: -1 # disable for issues
          days-before-pr-stale: 10
          days-before-pr-close: 0.1
          stale-pr-message: This pull request is now marked as stale because it hasn't seen activity for a while.
          close-pr-message: Closing this pull request as it hasn't seen activity for a while.
          stale-pr-label: 'stale' # The label that will be added manually to be marked as stale.
          exempt-pr-labels: 'awaiting-approval,work-in-progress,WIP' # Labels to skip to be marked as stale.
          #any-of-pr-labels: 'check,ra,test,feat,docs' # It's only processed if it contains any of the following labels
          #start-date: '2022-03-21T00:00:00Z' # The start date is used to ignore the issues and PRs created before the start date.