name: "Release-me action"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_PATH: "tf/p1"
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p test-commit-assets/ && echo "$(openssl rand -base64 20)" > test-commit-assets/data.txt

      #- run: tar czf dar-$(date +%Y%m%d-%H%M%S).tar.gz test-commit-assets/
      - run: tar czf dar-test.tar.gz test-commit-assets/

      - name: Release
        id: build_package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: ridedott/release-me-action@v3.6.23
        with:
          release-branches: '["main", "master"]'
          node-module: false
          disable-changelog: false
          release-assets: |
            ./dar-test.tar.gz
          commit-assets: |
            ./test-commit-assets/
