
name: "Terraform cache"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_PATH: "tf/p1"
    steps:
      - uses: actions/checkout@v2

      - name: Release
        id: build_package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: ridedott/release-me-action@v3.6.23
        with:
          release-branches: '["main", "master"]'
          node-module: false
          disable-changelog: false
          commit-assets: |
            ./