
name: "Terraform cache"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_PATH: "tf/p1"
    steps:

      - uses: actions/checkout@v2


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.6

      - run: "echo $GITHUB_WORKSPACE"

      - name: Cache Terraform
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/${{ env.TF_PATH }}/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - run: ls

      - name: Run Init
        working-directory: ${{ env.TF_PATH }}
        run: terraform init

      - name: Run Plan
        working-directory: ${{ env.TF_PATH }}
        run: terraform plan