name: "Workflow Dispatcher"

on:
  workflow_dispatch:
    inputs:
      env:
        type: environment
        required: true
        description: "Environment"
      dry_run:
        type: boolean
        required: false
        default: false
        description: Dry run mode

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Debug
        run: echo "${{ toJSON(github) }}"

      - name: Debug
        if: github.event.inputs.dry_run == 'false'
        run: echo "${{ github.event.inputs.dry_run }}"

      - name: Debug
        if: github.event.inputs.dry_run == false
        run: echo "${{ github.event.inputs.dry_run }}"

      - name: Install git-crypt
        env:
          VERSION: "0.6.0"
        run: |
          git clone -b "$VERSION" https://github.com/AGWA/git-crypt.git git-crypt
          cd git-crypt && make && make install PREFIX=/opt/project
          echo "/opt/project/bin" >> $GITHUB_PATH

      - name: Debug 3
        run: git-crypt --version

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Debug 3
        run: git-crypt --version
